# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
