# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20170916_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='test',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='ingrediententry',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingrediententry',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingrediententry',
            name='name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='ingrediententry',
            name='part',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='ingrediententry',
            name='post_comment',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='ingrediententry',
            name='pre_comment',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
