# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_ingrediententry_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientEntry',
            new_name='Ingredient',
        ),
    ]
