# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_auto_20170919_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cusine',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_url',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
