# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_auto_20170919_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='part',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='post_comment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='pre_comment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
