# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_auto_20170919_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cusine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
